sudo: required
dist: trusty
language: node_js
services:
  - docker
node_js:
- '7'
cache:
  directories:
    - node_modules
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
env:
  - NODE_ENV=production
install:
  - npm i --dev
script:
  - npm t
  - npm run build
  - docker build -t dvoicescuks/wowanalyzer:latest .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push dvoicescuks/wowanalyzer:latest;
    fi
